vim.o.wrap = true
vim.o.textwidth = 79
vim.o.formatoptions = "qrn1"
vim.o.sw = 4
vim.o.clipboard = "unnamedplus"
vim.o.relativenumber = true
vim.o.number = true
-- vim.o.formatoptions -= "cro"
vim.o.backupdir = "~/.cache/vim"
vim.o.mouse = "v"
vim.o.mouse = "a"
-- vim.o.noshowmode = true
vim.o.encoding = "UTF-8"
vim.o.guifont = "*"
vim.o.shiftwidth = 4
vim.o.updatetime = 100
vim.o.scrolloff = 7
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.splitbelow = true
vim.o.splitright = true
vim.o.autoindent = true
vim.opt.listchars = {
    tab = "| ",
    eol = '¬',
    trail = '·'
}
vim.o.list = true
vim.o.pyx = 3
